"""
Template renderer for RDTL.

Evaluates the AST and produces HTML output.
"""

from collections.abc import Callable
from typing import Any

from rdtl import ast_nodes
from rdtl.parser import parse


class RenderContext:
    """Rendering context holding variables and state.

    The context maintains a stack of variable frames for template variable
    resolution. Variables are looked up from innermost (most recent) to
    outermost frame.

    Note on type safety: Context values use 'Any' because Django templates
    accept any Python value at runtime. The template system must handle
    objects of any type - built-ins (str, int, list, dict), custom classes,
    Django models, etc. This is unavoidable for a dynamic template system.
    """

    def __init__(self, context: dict[str, Any] | None = None):
        """Initialize context with optional initial variables.

        Args:
            context: Initial variable bindings (default: empty dict).
        """
        self.stack: list[dict[str, Any]] = [context or {}]

    def push(self, new_context: dict[str, Any] | None = None):
        """Push a new context frame onto the stack.

        Args:
            new_context: Variables for the new frame (default: empty dict).
        """
        self.stack.append(new_context or {})

    def pop(self):
        """Pop the topmost context frame.

        The bottom frame is never popped to maintain a base context.
        """
        if len(self.stack) > 1:
            self.stack.pop()

    def get(self, name: str, default: Any = None) -> Any:
        """Get a variable from the context, searching innermost to outermost.

        Args:
            name: Variable name to look up.
            default: Value to return if variable not found.

        Returns:
            The variable value if found, otherwise the default value.
        """
        # Search from innermost to outermost
        for frame in reversed(self.stack):
            if name in frame:
                return frame[name]
        return default

    def set(self, name: str, value: Any) -> None:
        """Set a variable in the current (topmost) context frame.

        Args:
            name: Variable name.
            value: Value to bind (can be any Python object).
        """
        self.stack[-1][name] = value


class Renderer(ast_nodes.ASTVisitor):
    """Renders RDTL template AST to HTML using the Visitor pattern.

    The Renderer traverses the AST generated by the Parser and produces
    HTML output. It implements the Visitor pattern, with a visit method
    for each AST node type.

    Rendering Process:
        1. Initialize with context variables
        2. Call render() with the AST root node
        3. Visitor methods traverse the tree recursively
        4. Each node type has a specialized visit_* method
        5. Output is accumulated in an internal buffer
        6. Final HTML string is returned

    Context Management:
        The renderer maintains a RenderContext with a stack-based variable
        scope system. Variables are resolved from innermost to outermost scope:
        - Global context (provided at initialization)
        - Block scopes (from {% with %} blocks)
        - Loop scopes (from {% for %} blocks)

    Built-in Filters:
        The renderer includes several Django-compatible template filters:
        - upper: Uppercase transformation
        - lower: Lowercase transformation
        - title: Title case transformation
        - length: Get length of sequences
        - default: Provide fallback for empty/None values
        - truncatewords: Truncate text to N words
        - date: Date formatting (simplified)

    HTML Escaping:
        All variable output is automatically HTML-escaped to prevent XSS:
        - & → &amp;
        - < → &lt;
        - > → &gt;
        - " → &quot;
        - ' → &#x27;

    Expression Evaluation:
        The renderer evaluates Django's dot-notation lookups:
        1. Dictionary key lookup: obj['key']
        2. Attribute access: obj.attr
        3. List index: list[0]

        Lookups fail silently, returning None rather than raising errors.

    Usage:
        # Simple rendering
        renderer = Renderer(context={'user': {'name': 'Alice'}})
        output = renderer.render(ast)

        # With filters
        context = {'text': 'hello world'}
        renderer = Renderer(context)
        # Template: {{ text|upper|truncatewords:1 }}
        # Output: "HELLO..."

    Thread Safety:
        Renderer instances are NOT thread-safe. Each render() call mutates
        the output buffer and context. Create separate Renderer instances
        for concurrent rendering.
    """

    def __init__(self, context: dict[str, Any] | None = None):
        self.context = RenderContext(context)
        self.output: list[str] = []

        # Built-in filters
        self.filters: dict[str, Callable[..., Any]] = {
            "upper": lambda x: str(x).upper(),
            "lower": lambda x: str(x).lower(),
            "title": lambda x: str(x).title(),
            "length": lambda x: len(x) if hasattr(x, "__len__") else 0,
            "default": lambda x, d="": x if x else d,
            "truncatewords": self._filter_truncatewords,
            "date": self._filter_date,
        }

    def render(self, node: ast_nodes.ASTNode) -> str:
        """Render a template AST to HTML string."""
        self.output = []
        self.visit(node)
        return "".join(self.output)

    def write(self, text: str):
        """Append text to output."""
        self.output.append(text)

    # ========================================================================
    # Visitor methods
    # ========================================================================

    def visit_Document(self, node: ast_nodes.Document):
        """Render the document."""
        for child in node.children:
            self.visit(child)

    def visit_HTMLElement(self, node: ast_nodes.HTMLElement):
        """Render an HTML element."""
        # Opening tag
        self.write(f"<{node.tag_name}")

        # Attributes
        for attr in node.attributes:
            if attr.value is not None:
                # Escape attribute values
                escaped_value = self._escape_attr(attr.value)
                self.write(f' {attr.name}="{escaped_value}"')
            else:
                # Boolean attribute
                self.write(f" {attr.name}")

        self.write(">")

        # Children
        for child in node.children:
            self.visit(child)

        # Closing tag
        self.write(f"</{node.tag_name}>")

    def visit_VoidElement(self, node: ast_nodes.VoidElement):
        """Render a void HTML element."""
        self.write(f"<{node.tag_name}")

        for attr in node.attributes:
            if attr.value is not None:
                escaped_value = self._escape_attr(attr.value)
                self.write(f' {attr.name}="{escaped_value}"')
            else:
                self.write(f" {attr.name}")

        self.write(">")

    def visit_TextNode(self, node: ast_nodes.TextNode):
        """Render plain text."""
        self.write(node.content)

    def visit_Variable(self, node: ast_nodes.Variable):
        """Render a template variable."""
        # Evaluate the expression
        value = self._eval_expression(node.expression)

        # Apply filters
        for filter_node in node.filters:
            value = self._apply_filter(value, filter_node)

        # Convert to string and escape
        self.write(self._escape_html(str(value)))

    def visit_IfBlock(self, node: ast_nodes.IfBlock):
        """Render an if/elif/else block."""
        # Evaluate if condition
        if self._eval_condition(node.if_condition):
            for child in node.if_children:
                self.visit(child)
            return

        # Try elif branches
        for condition, children in node.elif_branches:
            if self._eval_condition(condition):
                for child in children:
                    self.visit(child)
                return

        # Else branch
        if node.else_children is not None:
            for child in node.else_children:
                self.visit(child)

    def visit_ForBlock(self, node: ast_nodes.ForBlock):
        """Render a for loop."""
        # Evaluate the iterable
        if node.iterable is None:
            iterable = []
        else:
            iterable = self._eval_expression(node.iterable)

        # Convert to list if needed
        if not hasattr(iterable, "__iter__"):
            iterable = []

        items = list(iterable)

        # If empty, render empty block
        if not items and node.empty_children is not None:
            for child in node.empty_children:
                self.visit(child)
            return

        # Render loop
        for item in items:
            # Push new context with loop variable(s)
            # Support both single variable and tuple unpacking
            if len(node.loop_vars) == 1:
                self.context.push({node.loop_vars[0]: item})
            else:
                # Tuple unpacking: {% for key, value in items %}
                if isinstance(item, (list, tuple)) and len(item) == len(node.loop_vars):
                    ctx = dict(zip(node.loop_vars, item))
                    self.context.push(ctx)
                else:
                    # If item doesn't match, just use the item for all variables
                    self.context.push({var: item for var in node.loop_vars})

            # Render children
            for child in node.children:
                self.visit(child)

            # Pop context
            self.context.pop()

    def visit_BlockTag(self, node: ast_nodes.BlockTag):
        """Render a block tag (simplified - no inheritance)."""
        # For now, just render the children
        for child in node.children:
            self.visit(child)

    def visit_WithBlock(self, node: ast_nodes.WithBlock):
        """Render a with block."""
        # Create new context with assignments
        new_context = {}
        for var_name, expr in node.assignments:
            new_context[var_name] = self._eval_expression(expr)

        self.context.push(new_context)

        # Render children
        for child in node.children:
            self.visit(child)

        self.context.pop()

    def visit_IncludeTag(self, node: ast_nodes.IncludeTag):
        """Render an include tag."""
        # Simplified: just output a comment
        self.write(f"<!-- include: {node.template_name} -->")

    def visit_ExtendsTag(self, node: ast_nodes.ExtendsTag):
        """Render an extends tag."""
        # Simplified: just output a comment
        self.write(f"<!-- extends: {node.parent_template} -->")

    def visit_LoadTag(self, node: ast_nodes.LoadTag):
        """Render a load tag."""
        # Simplified: no output (load tags don't produce HTML)
        pass

    def visit_CsrfTokenTag(self, node: ast_nodes.CsrfTokenTag):
        """Render a CSRF token tag."""
        # Simplified: output a placeholder
        self.write(
            '<input type="hidden" name="csrfmiddlewaretoken" value="csrf_token_placeholder">'
        )

    def visit_Comment(self, node: ast_nodes.Comment):
        """Render a template comment (don't output anything)."""
        # Template comments are not rendered
        pass

    # ========================================================================
    # Expression evaluation
    # ========================================================================

    def _eval_expression(
        self,
        expr: ast_nodes.Expression | ast_nodes.Literal | ast_nodes.FilteredExpression,
    ) -> Any:
        """Evaluate an expression to a value."""
        if isinstance(expr, ast_nodes.Literal):
            return expr.value

        if isinstance(expr, ast_nodes.FilteredExpression):
            # Evaluate the base expression first
            value = self._eval_expression(expr.expression)
            # Apply filters
            for filter_node in expr.filters:
                value = self._apply_filter(value, filter_node)
            return value

        if isinstance(expr, ast_nodes.Expression):
            # Get base variable
            value = self.context.get(expr.base)

            # Apply lookups
            for lookup in expr.lookups:
                if lookup.type == "attribute":
                    # Attribute access - prioritize dict keys over attributes
                    # Type narrow: attribute lookups always use string names
                    if not isinstance(lookup.value, str):
                        value = None
                        break
                    if isinstance(value, dict) and lookup.value in value:
                        value = value[lookup.value]
                    elif hasattr(value, lookup.value):
                        value = getattr(value, lookup.value)
                    else:
                        value = None
                        break

                elif lookup.type == "index":
                    # Index access
                    try:
                        value = value[lookup.value]
                    except (KeyError, IndexError, TypeError):
                        value = None
                        break

            return value

        return None

    def _eval_condition(self, condition: ast_nodes.Condition) -> bool:
        """Evaluate a condition to a boolean."""
        if isinstance(condition, ast_nodes.SimpleCondition):
            value = self._eval_expression(condition.expression)
            result = self._is_truthy(value)
            return not result if condition.negated else result

        elif isinstance(condition, ast_nodes.Comparison):
            left = self._eval_expression(condition.left)
            right = self._eval_expression(condition.right)

            if condition.operator == "==":
                return left == right
            elif condition.operator == "!=":
                return left != right
            elif condition.operator == "<":
                return left < right
            elif condition.operator == ">":
                return left > right
            elif condition.operator == "<=":
                return left <= right
            elif condition.operator == ">=":
                return left >= right
            elif condition.operator == "in":
                return left in right if right else False

        elif isinstance(condition, ast_nodes.BooleanOp):
            if condition.operator == "and":
                return all(self._eval_condition(c) for c in condition.operands)
            elif condition.operator == "or":
                return any(self._eval_condition(c) for c in condition.operands)

        return False

    def _is_truthy(self, value: Any) -> bool:
        """Determine if a value is truthy."""
        if value is None or value is False:
            return False
        if value == 0 or value == "":
            return False
        if hasattr(value, "__len__") and len(value) == 0:
            return False
        return True

    # ========================================================================
    # Filters
    # ========================================================================

    def _apply_filter(self, value: Any, filter_node: ast_nodes.Filter) -> Any:
        """Apply a filter to a value."""
        filter_name = filter_node.name

        if filter_name not in self.filters:
            # Unknown filter - just return the value
            return value

        filter_func = self.filters[filter_name]

        # Apply filter with arguments
        if filter_node.args:
            return filter_func(value, *filter_node.args)
        else:
            return filter_func(value)

    def _filter_truncatewords(self, value: str, num_words: int = 30) -> str:
        """Truncate text to a number of words."""
        words = str(value).split()
        if len(words) <= num_words:
            return str(value)
        return " ".join(words[:num_words]) + "..."

    def _filter_date(self, value: Any, format_str: str = "%Y-%m-%d") -> str:
        """Format a date (simplified)."""
        # Simplified: just return string representation
        return str(value)

    # ========================================================================
    # HTML escaping
    # ========================================================================

    def _escape_html(self, text: str) -> str:
        """Escape HTML special characters."""
        return (
            text.replace("&", "&amp;")
            .replace("<", "&lt;")
            .replace(">", "&gt;")
            .replace('"', "&quot;")
            .replace("'", "&#x27;")
        )

    def _escape_attr(self, text: str) -> str:
        """Escape attribute values."""
        return (
            text.replace("&", "&amp;")
            .replace("<", "&lt;")
            .replace(">", "&gt;")
            .replace('"', "&quot;")
        )


def render(template: str, context: dict[str, Any] | None = None) -> str:
    """
    Convenience function to parse and render a template.

    Args:
        template: RDTL template string
        context: Dictionary of variables for the template

    Returns:
        Rendered HTML string
    """
    ast = parse(template)
    renderer = Renderer(context)
    return renderer.render(ast)


if __name__ == "__main__":
    # Test the renderer
    template = """
    <div class="container">
        {% if user %}
            <h1>Hello {{ user.name|upper }}!</h1>
            <p>Email: {{ user.email }}</p>

            <h2>Items</h2>
            <ul>
                {% for item in user.items %}
                    <li>{{ item.title }} - {{ item.price }}</li>
                {% empty %}
                    <li>No items found</li>
                {% endfor %}
            </ul>
        {% else %}
            <p>Please log in</p>
        {% endif %}
    </div>
    """

    context = {
        "user": {
            "name": "Alice",
            "email": "alice@example.com",
            "items": [
                {"title": "Book", "price": "$10"},
                {"title": "Pen", "price": "$2"},
            ],
        }
    }

    output = render(template, context)
    print(output)
